version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - marine_net
    
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: always
    networks:
      - marine_net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    restart: always
    networks:
      - marine_net

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped
    networks:
      - marine_net

  create_buckets:
    image: python:3.9
    container_name: create_buckets
    depends_on:
      - minio
    volumes:
      - ./setup_minio:/scripts
    working_dir: /scripts
    command: ["sh", "-c", "pip install boto3 && python create_minio_buckets.py"]
    restart: "no"
    networks:
      - marine_net

  satellite_producer:
    build:
      context: ./satellite_producer 
    container_name: satellite_producer
    depends_on:
      - kafka
      - minio
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=satellite_imagery
      - FETCH_INTERVAL_SECONDS=900
      - SH_CLIENT_ID=sh-eb560cfe-5964-4ac6-a0b0-d87c8e03af4b
      - SH_CLIENT_SECRET=qZywwuvH6Bqq0TmbDuoNkW9SxgTVO4HA
      - SH_TOKEN_URL=https://identity.dataspace.copernicus.eu/auth/realms/CDSE/protocol/openid-connect/token
      - SH_BASE_URL=https://sh.dataspace.copernicus.eu
      - MINIO_ENDPOINT=minio:9000
      - MINIO_BUCKET=bronze
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    restart: always
    networks:
      - marine_net

  buoy_producer:
    build:
      context: ./buoy_producer
    container_name: buoy_producer
    depends_on:
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=buoy_data
      - GENERATE_INTERVAL_SECONDS=30
    restart: always
    networks:
      - marine_net

  data_processor_job:
    build:
      context: ./data_processor
    container_name: data_processor_job
    ports:
      - "8082:8081"
    depends_on:
      - kafka
      - minio
      - create_buckets
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_SERVERS=kafka:9092
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - MINIO_ENDPOINT=minio:9000
      - BUOY_TOPIC=buoy_data
      - SATELLITE_TOPIC=satellite_imagery
      - PROCESSED_DATA_TOPIC=processed_data
    restart: on-failure
    networks:
      - marine_net

  pollution_analyzer_job:
    build:
      context: ./pollution_analyzer
    container_name: pollution_analyzer_job
    ports:
      - "8083:8081"
    depends_on:
      - kafka
      - minio
      - redis
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_SERVERS=kafka:9092
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - MINIO_ENDPOINT=minio:9000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - BUOY_TOPIC=buoy_data
      - SATELLITE_TOPIC=satellite_imagery
      - ANALYZED_DATA_TOPIC=analyzed_data
      - HOTSPOTS_TOPIC=pollution_hotspots
      - ALERTS_TOPIC=sensor_alerts
    restart: on-failure
    networks:
      - marine_net

  ml_prediction_job:
    build:
      context: ./ml_prediction
    container_name: ml_prediction_job
    ports:
      - "8084:8081"
    depends_on:
      - kafka
      - minio
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_SERVERS=kafka:9092
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - MINIO_ENDPOINT=minio:9000
      - BUOY_TOPIC=buoy_data
      - SATELLITE_TOPIC=satellite_imagery
      - PREDICTIONS_TOPIC=pollution_predictions
    restart: on-failure
    networks:
      - marine_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=redis-datasource,grafana-worldmap-panel,grafana-piechart-panel
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - marine_net
    depends_on:
      - redis
    

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=marine_pollution
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - marine_net
    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=marine_pollution
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    networks:
      - marine_net
    restart: unless-stopped

  alert_manager:
    build:
      context: ./alert_manager
    container_name: alert_manager
    depends_on:
      - kafka
      - redis
      - postgres
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=marine_pollution
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - ALERTS_TOPIC=sensor_alerts
      - NOTIFICATIONS_TOPIC=notifications
    volumes:
      - ./common:/app/common
    networks:
      - marine_net
    restart: on-failure

  dashboard_consumer:
    build:
      context: ./dashboard_consumer
    container_name: dashboard_consumer
    depends_on:
      - kafka
      - redis
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./common:/app/common
    networks:
      - marine_net
    restart: on-failure

  storage_consumer:
    build:
      context: ./storage_consumer
    container_name: storage_consumer
    depends_on:
      - kafka
      - timescaledb
      - minio
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - TIMESCALE_HOST=timescaledb
      - TIMESCALE_DB=marine_pollution
      - TIMESCALE_USER=postgres
      - TIMESCALE_PASSWORD=postgres
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - ANALYZED_TOPIC=analyzed_data
      - HOTSPOTS_TOPIC=pollution_hotspots
      - PREDICTIONS_TOPIC=pollution_predictions
      - ALERTS_TOPIC=sensor_alerts
    networks:
      - marine_net
    restart: on-failure

networks:
  marine_net:
    driver: bridge

volumes:
  minio_data:
  grafana_data:
  postgres_data:
  timescaledb_data: