global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'marine-services'
    static_configs:
      - targets: 
        - 'dashboard:8501'
        - 'buoy_producer:8080'
        - 'satellite_producer:8080'
        - 'storage_consumer:8080'
        - 'alert_manager:8080'
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'timescale'
    static_configs:
      - targets: ['timescaledb:5432']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
