[default-profile]
sh_client_id = "your_client_id"
sh_client_secret = "your_secret_key"
sh_base_url = "https://sh.dataspace.copernicus.eu"
sh_token_url = "https://identity.dataspace.copernicus.eu/auth/realms/CDSE/protocol/openid-connect/token"