global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "rules/recording_rules.yml"
  - "rules/alert_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "flink-jobmanager"
    metrics_path: /metrics
    static_configs:
      - targets: ["jobmanager:9249"]

  - job_name: "flink-taskmanager"
    metrics_path: /metrics
    static_configs:
      - targets: ["taskmanager:9249"]

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka:9308"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "minio"
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ["minio:9000"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "sensor_analyzer"
    static_configs:
      - targets: ["sensor_analyzer:8000"]

  - job_name: "image_standardizer"
    static_configs:
      - targets: ["image_standardizer:8000"]

  - job_name: "pollution_detector"
    static_configs:
      - targets: ["pollution_detector:8000"]

  - job_name: "ml_prediction"
    static_configs:
      - targets: ["ml_prediction:8000"]

  - job_name: "dashboard_consumer"
    static_configs:
      - targets: ["dashboard_consumer:8000"]

  - job_name: "alert_manager"
    static_configs:
      - targets: ["alert_manager:8000"]