[default-profile]
sh_client_id = "84efe9ee-9215-49d0-80c4-9bd77cb6b2f8"
sh_client_secret = "6eXIVZxIVZcua1RcNW1tlMCUEcm34eQH"
sh_base_url = "https://sh.dataspace.copernicus.eu"
sh_token_url = "https://identity.dataspace.copernicus.eu/auth/realms/CDSE/protocol/openid-connect/token"